- type: frontend
  label: Frontend
  tech:
    - - (P)React
      - CSS / SASS
      - Redux
      - Foundation
- type: backend
  label: Backend
  tech:
    - - Node.js
      - TypeScript
      - Express.js
      - MQTT
    - - PHP
      - WordPress
      - Symphony
- type: db
  label: Datenbank
  tech:
    - - PostgreSQL
      - MySQL
      - MongoDB
      - CouchDB
      - Oracle DB
- type: cicd
  label: CI & CD
  tech:
    - - Docker
      - Travis CI
      - Mocha
      - Webpack
      - Gulp
- type: foundation
  label: Basis
  tech:
    - - Linux
      - AWS
      - nginx
      - Git
      - REST
      - Elasticsearch
      - Authentifizierung
      - WebSockets
      - Jira
      - Confluence
      - UML
