title: Manuel Sch채chinger
url: https://github.schaechinger.com
description: "Hi, ich bin Manuel. Ein leidenschaftlicher JavaScript Entwickler aus M체nchen. Hier findest du neben meinem bisherigen Werdegang auch Informationen zu meinen Projekten und Ausz체ge aus meinem Leben im Blog."
lang: de_DE
author: Manuel Sch채chinger
permalink: /blog/:year-:title

imageBase: https://images.schaechinger.com

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

defaults:
  - scope:
      path: "."
      type: "drafts"
    values:
      sitemap: false

ga: UA-70769809-1

maps:
  google:
    key: "AIzaSyA5M0ChH7z265Ypy6LLg8NIloj2ZHiADms"

twitter:
  username: theschaechinger

social:
  links:
    - https://twitter.com/theschaechinger
    - https://www.facebook.com/schaechinger
    - https://www.linkedin.com/in/schaechinger
    - https://github.com/schaechinger
    - https://keybase.io/schaechinger

sass:
  style: compressed
