title: schaechinger.com
url: http://gh.schaechinger.com
description: "In meinem Blog dreht sich alles um Laufen, Reisen und Webentwicklung mit JavaScript und Node.js."
author: Manuel Schächinger
permalink: /blog/:year-:title

imageBase: https://images.schaechinger.com

plugins:
  - jekyll-feed
  - jekyll-maps
  - jekyll-redirect-from
  - jekyll-sitemap

maps:
  google:
    api_key: AIzaSyA5M0ChH7z265Ypy6LLg8NIloj2ZHiADms
    marker_cluster:
      enabled: false

markdown: kramdown

sass:
  style: compressed
