title: Manuel Schächinger
url: https://www.schaechinger.com
description: "Hi, ich bin Manuel. Freiberuflicher JavaScript Engineer und Consultant für komplexe Softwaresysteme in München sowie remote. Erfahren Sie mehr über meine Tätigkeit und die aktuelle Verfügbarkeit."
lang: de_DE
author: Manuel Schächinger
permalink: /blog/:year-:title

imageBase: https://images.schaechinger.com

plugins:
  - jekyll-seo-tag

markdown: kramdown

defaults:
  - scope:
      path: "."
      type: "drafts"
    values:
      sitemap: false

ga: UA-70769809-1
gc: 6LeKUpkUAAAAAN_-USqhkSfW4KGK1e71HKGfQuNG

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

maps:
  google:
    key: "AIzaSyA5M0ChH7z265Ypy6LLg8NIloj2ZHiADms"

twitter:
  username: theschaechinger
  card: summary

social:
  name: Manuel Schächinger
  links:
    - https://twitter.com/theschaechinger
    - https://linkedin.com/in/schaechinger
    - https://github.com/schaechinger
    - https://keybase.io/schaechinger

contact:
  phone: +49 160 97506593

sass:
  style: compressed
