title: schaechinger.com
url: http://gh.schaechinger.com
description: "In meinem Blog dreht sich alles um Laufen, Reisen und Webentwicklung mit JavaScript und Node.js."
author: Manuel Schächinger
permalink: /blog/:year-:title

imageBase: https://images.schaechinger.com

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

markdown: kramdown

sass:
  style: compressed
