title: Manuel Schächinger
url: https://www.schaechinger.com
description: "Hi, ich bin Manuel. Ein leidenschaftlicher JavaScript Entwickler aus München. Hier findest du neben meinem bisherigen Werdegang auch Informationen zu meinen Projekten und Auszüge aus meinem Leben im Blog."
lang: de_DE
author: Manuel Schächinger
permalink: /blog/:year-:title

imageBase: https://images.schaechinger.com

plugins:
  - jekyll-seo-tag

markdown: kramdown

defaults:
  - scope:
      path: "."
      type: "drafts"
    values:
      sitemap: false

ga: UA-70769809-1

maps:
  google:
    key: "AIzaSyA5M0ChH7z265Ypy6LLg8NIloj2ZHiADms"

twitter:
  username: theschaechinger
  card: summary

social:
  name: Manuel Schächinger
  links:
    - https://twitter.com/theschaechinger
    - https://www.facebook.com/schaechinger
    - https://www.linkedin.com/in/schaechinger
    - https://github.com/schaechinger
    - https://keybase.io/schaechinger

sass:
  style: compressed
