title: schaechinger.com
url: http://github.schaechinger.com
description: "Hi, ich bin Manuel. Ein leidenschaftlicher JavaScript Entwickler aus München. Hier findest du neben meinem bisherigen Werdegang auch Informationen zu meinen Projekten und Auszüge aus meinem Leben im Blog."
author: Manuel Schächinger
permalink: /blog/:year-:title

imageBase: https://images.schaechinger.com

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

markdown: kramdown

sass:
  style: compressed
